CREATE TABLE [dbo].[VIN] (
	[VINID]	int not null IDENTITY,
    [ECDID] INT       NOT NULL, 
    [VIN]    NCHAR (50) NOT NULL,
    CONSTRAINT [PK_VIN] PRIMARY KEY ([VINID]), 
    CONSTRAINT [FK_VIN_ECD] FOREIGN KEY ([ECDID]) REFERENCES [ECD]([ECDID]), 
);


GO

CREATE UNIQUE INDEX [IX_VIN_VIN] ON [dbo].[VIN] ([VIN])
